# Generated by Django 3.1.1 on 2020-09-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vagt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField()),
                ('status', models.CharField(max_length=64)),
                ('person', models.CharField(max_length=64)),
            ],
        ),
    ]
